apiVersion: v2
appVersion: 1.2.2
description: A Helm chart for csi-neonio
home: https://github.com/qingstor/neonio/
icon: https://s3.qingcloud.com/files/2021/02/qing-stor-neon-san.png
keywords:
- neonio
kubeVersion: '>=1.17.0-0'
maintainers:
- email: hansyang@yunify.com
  name: Yangxingxiang
name: csi-neonio
sources:
- https://github.com/qingstor/neonio/
version: 1.2.3
